/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsElectromagneticBrakingRouteImport } from './routes/projects.electromagnetic-braking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsElectromagneticBrakingRoute =
  ProjectsElectromagneticBrakingRouteImport.update({
    id: '/projects/electromagnetic-braking',
    path: '/projects/electromagnetic-braking',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/electromagnetic-braking': typeof ProjectsElectromagneticBrakingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/electromagnetic-braking': typeof ProjectsElectromagneticBrakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/electromagnetic-braking': typeof ProjectsElectromagneticBrakingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/electromagnetic-braking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/electromagnetic-braking'
  id: '__root__' | '/' | '/projects/electromagnetic-braking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsElectromagneticBrakingRoute: typeof ProjectsElectromagneticBrakingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/electromagnetic-braking': {
      id: '/projects/electromagnetic-braking'
      path: '/projects/electromagnetic-braking'
      fullPath: '/projects/electromagnetic-braking'
      preLoaderRoute: typeof ProjectsElectromagneticBrakingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsElectromagneticBrakingRoute: ProjectsElectromagneticBrakingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
